"""`harness-runtime` — H_T composition root.

Per `CLAUDE.md` §3.3 and `design-substrate/Spec_Harness_Runtime_v1.md` v1.1,
this package owns runtime composition of the axis libraries:

- Bootstrap orchestration (9 stages per C-RT-01).
- Provider SDK lifecycle (F-P2-4; C-RT-05).
- TracerProvider lifecycle (F-P2-3; C-RT-06).
- In-process OTLP collector daemon supervision (F-P2-5; C-RT-07).
- Cross-axis seam wiring (C-RT-12; 24 phase-2-runtime edges).
- `run()` Python API (F-P2-2; C-RT-08).

Foundational package scaffold traceability lands here as U-RT-01: the runtime
workspace package is importable and exposes the composition-root public API.
Public API surface lands at L8 close (U-RT-42 — `run()` signature + `RunResult`
shape) and L9 (U-RT-43 — bootstrap orchestrator body).
"""

from __future__ import annotations

from harness_runtime.api import (
    ConcurrentRunNotSupported,
    FailureCause,
    HarnessDraining,
    InvalidWorkflowError,
    ResumeArgsError,
    ResumeHandleUnknownError,
    ResumeProtocolNotBoundError,
    ResumeStepIndexOutOfRangeError,
    ResumeWorkflowMismatchError,
    RunResult,
    WorkflowObject,
    resume,
    run,
)
from harness_runtime.bootstrap import (
    BootstrapFailure,
    BootstrapStageCompleteEvent,
    IncompleteBootstrapError,
    run_bootstrap,
)
from harness_runtime.cli_profile_loading import (
    CliExternalMemorySourceAccess,
    CliProfileResolution,
    CliProfileResolutionError,
    CliProfileResolutionRequest,
    LoadedCliInstructionSource,
    resolve_cli_profile,
)
from harness_runtime.drain import DrainPlatformError
from harness_runtime.lifecycle.memory_migration import (
    CallbackMemoryMigrationService,
    MemoryMigrationItem,
    MemoryMigrationItemStatus,
    MemoryMigrationReport,
)
from harness_runtime.memory_capture import (
    EpisodicMemoryCapture,
    MemoryCaptureMode,
    MemoryCaptureResult,
    MemoryCaptureStatus,
    SummaryProvenance,
    SummarySource,
)
from harness_runtime.memory_compaction_safety import (
    CompactionCandidateDisposition,
    CompactionCandidateDispositionRecord,
    CompactionDecisionResult,
    CompactionDecisionStore,
    CompactionDispositionRequiredError,
    CompactionDispositionWriteError,
    CompactionSafetyHook,
)
from harness_runtime.memory_context import (
    MemoryContextCompositionRequest,
    MemoryInjectionOperationStore,
    RenderedMemoryPromptPacket,
    RuntimeMemoryContext,
    RuntimeMemoryContextComposer,
    compose_system_prompt_with_memory_packet,
    render_prompt_extension_packet,
)
from harness_runtime.memory_engine_durability import (
    MemoryDurabilityBinding,
    MemoryDurabilityCarrier,
    MemoryDurabilityDecision,
    MemoryDurabilityStrategy,
    MemoryDurabilityViolationError,
    memory_durability_binding_for,
    memory_durability_bindings,
    memory_operation_engine_class_for,
    validate_memory_durability,
)
from harness_runtime.memory_promotion import (
    PreferenceCandidateSource,
    PreferencePromotionDetails,
    PreferencePromotionValidationError,
    PreferenceSourceAuthority,
    PreferenceStrength,
    PreferenceSubject,
    PromotionCandidate,
    PromotionCandidateConfidence,
    PromotionCandidateExtractor,
    PromotionCandidateHint,
    PromotionCandidateKind,
    PromotionDecisionResult,
    PromotionDecisionService,
    PromotionDecisionStore,
    PromotionReviewRequiredError,
    PromotionRiskFlag,
    SemanticInjectionPolicy,
    SemanticRecordStatus,
)
from harness_runtime.memory_tool_executor import (
    MemoryToolExecutionContext,
    MemoryToolExecutionDeniedError,
    MemoryToolExecutionError,
    MemoryToolExecutionInputError,
    MemoryToolExecutionRequest,
    StandardMemoryToolExecutor,
)
from harness_runtime.memory_verification_suite import (
    ACCESS_MODE_VERIFICATION_SCENARIOS,
    C_MEM_20_REQUIREMENT_IDS,
    CLI_PROFILE_VERIFICATION_SCENARIOS,
    EXTERNAL_CLI_ROUTING_SCENARIOS,
    LIVE_CREDENTIAL_GATES,
    AccessModeVerificationScenario,
    CliProfileVerificationScenario,
    ExternalCliRoutingScenario,
    LiveCredentialGate,
    MemoryVerificationMatrix,
    VerificationEvidenceLane,
    VerificationRequirement,
    VerificationTestSelector,
    memory_verification_matrix,
)
from harness_runtime.shutdown import (
    AlreadyShutDown,
    FlushReport,
    FlushTimeoutError,
    ShutdownReport,
    ShutdownTimeout,
    flush_observability,
    shutdown,
)

__all__ = [
    "ACCESS_MODE_VERIFICATION_SCENARIOS",
    "CLI_PROFILE_VERIFICATION_SCENARIOS",
    "C_MEM_20_REQUIREMENT_IDS",
    "EXTERNAL_CLI_ROUTING_SCENARIOS",
    "LIVE_CREDENTIAL_GATES",
    "AccessModeVerificationScenario",
    "AlreadyShutDown",
    "BootstrapFailure",
    "BootstrapStageCompleteEvent",
    "CallbackMemoryMigrationService",
    "CliExternalMemorySourceAccess",
    "CliProfileResolution",
    "CliProfileResolutionError",
    "CliProfileResolutionRequest",
    "CliProfileVerificationScenario",
    "CompactionCandidateDisposition",
    "CompactionCandidateDispositionRecord",
    "CompactionDecisionResult",
    "CompactionDecisionStore",
    "CompactionDispositionRequiredError",
    "CompactionDispositionWriteError",
    "CompactionSafetyHook",
    "ConcurrentRunNotSupported",
    "DrainPlatformError",
    "EpisodicMemoryCapture",
    "ExternalCliRoutingScenario",
    "FailureCause",
    "FlushReport",
    "FlushTimeoutError",
    "HarnessDraining",
    "IncompleteBootstrapError",
    "InvalidWorkflowError",
    "LiveCredentialGate",
    "LoadedCliInstructionSource",
    "MemoryCaptureMode",
    "MemoryCaptureResult",
    "MemoryCaptureStatus",
    "MemoryContextCompositionRequest",
    "MemoryDurabilityBinding",
    "MemoryDurabilityCarrier",
    "MemoryDurabilityDecision",
    "MemoryDurabilityStrategy",
    "MemoryDurabilityViolationError",
    "MemoryInjectionOperationStore",
    "MemoryMigrationItem",
    "MemoryMigrationItemStatus",
    "MemoryMigrationReport",
    "MemoryToolExecutionContext",
    "MemoryToolExecutionDeniedError",
    "MemoryToolExecutionError",
    "MemoryToolExecutionInputError",
    "MemoryToolExecutionRequest",
    "MemoryVerificationMatrix",
    "PreferenceCandidateSource",
    "PreferencePromotionDetails",
    "PreferencePromotionValidationError",
    "PreferenceSourceAuthority",
    "PreferenceStrength",
    "PreferenceSubject",
    "PromotionCandidate",
    "PromotionCandidateConfidence",
    "PromotionCandidateExtractor",
    "PromotionCandidateHint",
    "PromotionCandidateKind",
    "PromotionDecisionResult",
    "PromotionDecisionService",
    "PromotionDecisionStore",
    "PromotionReviewRequiredError",
    "PromotionRiskFlag",
    "RenderedMemoryPromptPacket",
    "ResumeArgsError",
    "ResumeHandleUnknownError",
    "ResumeProtocolNotBoundError",
    "ResumeStepIndexOutOfRangeError",
    "ResumeWorkflowMismatchError",
    "RunResult",
    "RuntimeMemoryContext",
    "RuntimeMemoryContextComposer",
    "SemanticInjectionPolicy",
    "SemanticRecordStatus",
    "ShutdownReport",
    "ShutdownTimeout",
    "StandardMemoryToolExecutor",
    "SummaryProvenance",
    "SummarySource",
    "VerificationEvidenceLane",
    "VerificationRequirement",
    "VerificationTestSelector",
    "WorkflowObject",
    "compose_system_prompt_with_memory_packet",
    "flush_observability",
    "memory_durability_binding_for",
    "memory_durability_bindings",
    "memory_operation_engine_class_for",
    "memory_verification_matrix",
    "render_prompt_extension_packet",
    "resolve_cli_profile",
    "resume",
    "run",
    "run_bootstrap",
    "shutdown",
    "validate_memory_durability",
]
