#!/usr/bin/env bash
# Shared library for Claude Code hook scripts in this workspace.
#
# Sourced by tools/roadmap-audit/*.sh and tools/hooks/*.sh so every hook reuses
# ONE tested helper set instead of re-implementing the conventions — the
# anti-drift keystone of the U-HK-* autonomy-infrastructure plan. The functions
# are side-effect-free EXCEPT `hook_emit` (prints JSON + exits 0).
#
# Conventions preserved verbatim from the two original hooks (session-start.sh +
# post-merge-refresh.sh): the additionalContext JSON shape, the §12.1
# workspace_state_hash recipe, the portable bounded-run watchdog (stock-macOS
# safe), and the always-exit-0 / encode-failure-as-context discipline.
#
# Pure function library — do NOT `set -e` here (it would surprise the sourcing
# script). Test with tools/hooks/test_lib.sh.

# Resolve the workspace root: $CLAUDE_PROJECT_DIR (set by Claude Code) or the git
# toplevel. Echoes the path, empty if neither resolves.
# Usage: PROJECT_DIR=$(hook_project_dir); [ -z "$PROJECT_DIR" ] && exit 0
hook_project_dir() {
  local d="${CLAUDE_PROJECT_DIR:-$(git rev-parse --show-toplevel 2>/dev/null)}"
  printf '%s' "$d"
}

# Emit additionalContext JSON for a hook event and exit 0. Mirrors the original
# hooks' shape. Usage: hook_emit <hookEventName> <context-string>
hook_emit() {
  jq -nc --arg ev "$1" --arg ctx "$2" \
    '{"hookSpecificOutput":{"hookEventName":$ev,"additionalContext":$ctx}}'
  exit 0
}

# Read all of stdin (the hook payload JSON). Echoes it; empty on none.
hook_read_stdin() { cat 2>/dev/null || true; }

# Extract a jq path from a JSON payload with an empty-string default.
# Usage: CMD=$(hook_json "$PAYLOAD" '.tool_input.command')
hook_json() { printf '%s' "$1" | jq -r "$2 // empty" 2>/dev/null || true; }

# Default branch name (origin/HEAD symref), falling back to "main".
hook_default_branch() {
  local b
  b=$(git symbolic-ref --quiet --short refs/remotes/origin/HEAD 2>/dev/null | sed 's#^origin/##')
  printf '%s' "${b:-main}"
}

# Portable bounded runner: run a command, kill it if it outlives SECS — even on a
# stock macOS that ships neither GNU `timeout` nor `gtimeout`. Prefers the native
# binary when present; otherwise a pure-bash watchdog that ESCALATES SIGTERM →
# SIGKILL after a short grace, so a child stuck in an SSH / credential-helper path
# that ignores TERM is still force-killed (SIGKILL is uncatchable). `wait` then
# returns within SECS + grace — a genuine hard bound, never an indefinite hang.
# Returns the command's exit code (or the kill's). Usage: hook_bounded SECS cmd...
hook_bounded() {
  local secs="$1"; shift
  # `-k 2`: GNU timeout sends SIGTERM at SECS, then SIGKILL 2s later if the child
  # ignored TERM (without -k, `timeout` only sends TERM and WAITS — a TERM-ignoring
  # git-over-SSH would hang the hook). Both native paths and the pure-bash fallback
  # escalate to KILL, so this is a genuine hard bound everywhere. Invoke the binary
  # EXPLICITLY (not via an unquoted "$prefix $@" that relies on word-splitting — zsh
  # does not split unquoted vars, which would turn the prefix into one bogus argv0).
  if command -v timeout >/dev/null 2>&1; then
    timeout -k 2 "$secs" "$@"
    return $?
  fi
  if command -v gtimeout >/dev/null 2>&1; then
    gtimeout -k 2 "$secs" "$@"
    return $?
  fi
  "$@" & local p=$!
  (
    sleep "$secs"
    kill -0 "$p" 2>/dev/null || exit 0
    kill -TERM "$p" 2>/dev/null
    sleep 2
    kill -0 "$p" 2>/dev/null && kill -KILL "$p" 2>/dev/null
  ) >/dev/null 2>&1 & local w=$!
  wait "$p" 2>/dev/null; local rc=$?
  kill "$w" 2>/dev/null; wait "$w" 2>/dev/null
  return "$rc"
}

# The §12.1 step-2 workspace_state_hash recipe: sha256(head|prs|forks|batch)[:12].
# Usage: hook_state_hash <head8> <prs_csv> <forks_count> <batch_path>
hook_state_hash() {
  printf '%s|%s|%s|%s' "$1" "$2" "$3" "$4" | shasum -a 256 | head -c 12
}

# True iff the changed-file set of a commit is a §12.2.1 dashboard-only terminating
# refresh. §12.2.1 defines the allowed set as `.harness/roadmap_status.md` AND, when
# regenerated by tools/dashboard/generate.py, `tools/dashboard/roadmap.html` — so the
# set must be EXACTLY {roadmap_status.md} OR EXACTLY {roadmap_status.md, roadmap.html}.
# The prior single-file check (`= ".harness/roadmap_status.md"` inline at the 3 call
# sites) false-flagged every HTML-regenerating refresh as a substantive merge: a false
# SessionStart DRIFT, a false UserPromptSubmit drift note, AND a false post-merge
# "refresh owed" — the §12.2.1 recursion the fixed point exists to STOP.
#
# Closed-set (NOT "is-among") semantics are load-bearing: a substantive commit
# mis-titled with the reserved refresh prefix carries files outside the allowed pair,
# so it must NOT pass here (it correctly halts as DRIFT / emits "refresh owed").
# Input is the caller's `git show --name-only … | sort -u` output (sorted-unique,
# trailing-newline-stripped by command substitution).
# Usage: hook_is_dashboard_only_set "$CHANGED_FILES_SORTED_UNIQUE"
hook_is_dashboard_only_set() {
  local set="$1"
  local status=".harness/roadmap_status.md"
  local html="tools/dashboard/roadmap.html"
  [ "$set" = "$status" ] && return 0
  # `sort -u` orders ".harness/…" before "tools/…" ('.' 0x2e < 't' 0x74), so the
  # two-file set is exactly this two-line string.
  [ "$set" = "$(printf '%s\n%s' "$status" "$html")" ] && return 0
  return 1
}

# Extract the CURRENT roadmap next-action R-id from the dashboard. Scopes to the
# `## Next action` section (from that heading to the next `---` horizontal rule)
# and returns the FIRST backticked `R-NNN` token there. Scoping is the fix for the
# old whole-file `head -1` bug: the dashboard carries historical + narrative `R-*`
# references that precede the live pointer in document order (e.g. an `**`R-010`**`
# deep in the R-700 banner), so an unscoped match surfaced a stale item. Range
# tokens such as `R-410..R-440` are menus, not actionable units, so they are
# ignored. Echoes the R-id, empty if absent (callers default). Usage:
# NEXT=$(hook_roadmap_next "$DASHBOARD")
hook_roadmap_next() {
  local dash="$1"
  [ -f "$dash" ] || return 0
  local section current token
  section=$(awk '/^## Next action/{f=1; next} f && /^---$/{exit} f' "$dash" 2>/dev/null)
  current=$(printf '%s\n' "$section" | grep -m1 'Current next action' 2>/dev/null || true)
  token=$(printf '%s\n' "$current" \
    | sed -nE 's/.*next implementable unit is `?((U|R)-[A-Za-z0-9._-]+)`?.*/\1/p' \
    | grep -v '\.\.' \
    | head -1)
  if [ -n "$token" ]; then
    printf '%s' "$token"
    return 0
  fi
  printf '%s\n' "$section" \
    | grep -oE '`(U|R)-[A-Za-z0-9._-]+`' 2>/dev/null \
    | tr -d '`' \
    | grep -v '\.\.' \
    | head -1
}

# Write a lightweight state snapshot to .harness/.checkpoints/precompact-<ts>.md +
# precompact-latest.md (the file U-HK-06 postcompact-reinject reads; session-end-cleanup
# keep-10-prunes `precompact-2*.md`). Shared by precompact-checkpoint.sh (U-HK-05, at
# compaction) and the context-recovery statusline (U-HK-27, as context fills). Best-effort
# (never errors the caller). Args: <label> [skip_gh]. With skip_gh non-empty the open-PRs
# `gh` call is omitted — the statusline is a per-turn hot path and must stay fast + offline.
hook_write_checkpoint() {
  local label="$1" skip_gh="${2:-}"
  local d; d=$(hook_project_dir); [ -n "$d" ] || return 0
  local ckdir="$d/.harness/.checkpoints"
  mkdir -p "$ckdir" 2>/dev/null || return 0
  local ts head branch next prs dirty
  ts=$(date -u +%Y%m%d-%H%M%S 2>/dev/null || echo now)
  head=$(git -C "$d" rev-parse --short HEAD 2>/dev/null || echo "?")
  branch=$(git -C "$d" symbolic-ref --quiet --short HEAD 2>/dev/null || echo "?")
  next=$(hook_roadmap_next "$d/.harness/roadmap_status.md")
  if [ -z "$skip_gh" ]; then
    prs=$(hook_bounded 5 gh pr list --state open --json number,title --jq '.[]|"#\(.number) \(.title)"' 2>/dev/null | head -10)
  else
    prs="(skipped — fast path)"
  fi
  dirty=$(git -C "$d" status --short 2>/dev/null | head -30)
  local out="$ckdir/precompact-${ts}.md"
  {
    echo "# ${label} ${ts}"
    echo
    echo "- HEAD: \`${head}\` on \`${branch}\`"
    echo "- roadmap next-action: ${next:-?}"
    echo "- open PRs:"
    printf '%s\n' "${prs:-  (none)}" | sed 's/^/  - /'
    echo "- uncommitted:"
    printf '%s\n' "${dirty:-  (clean)}" | sed 's/^/  /'
  } > "$out" 2>/dev/null || return 0
  cp "$out" "$ckdir/precompact-latest.md" 2>/dev/null || true
}

# Loop-mode detection (Wave 2 autonomy gate). Returns 0 (true) when the autonomous
# loop is active. OFF by default — the autonomy hooks (auto-approve permissions,
# Stop-continue) MUST be inert unless this returns true, so normal interactive
# sessions are never auto-driven. Gate = HARNESS_LOOP=1 env OR a
# .harness/.loop-active marker file at the workspace root.
loop_mode_active() {
  [ "${HARNESS_LOOP:-}" = "1" ] && return 0
  local d; d=$(hook_project_dir)
  [ -n "$d" ] && [ -f "$d/.harness/.loop-active" ]
}

# Live-session detection for a git worktree. Removing a worktree out from under a live
# Claude session orphans it — the session's Edit/Write tools stay pinned to the deleted
# worktree root and reject every shared-checkout path (operator hit this 2026-06-04).
# Claude keys a session transcript by the worktree's ABSOLUTE physical path with every
# non-alphanumeric char mapped to '-', at ~/.claude/projects/<encoded>/<session>.jsonl
# (verified against the real dir). A transcript touched within the liveness window ⇒ a
# session is active there. Window default 30 min; override via env. Consumed by the
# permission-guard §0 deny AND loop-gc's reap gate.
#
# worktree_has_live_session <worktree_path>  → 0 (true) iff a live session is detected.
# Fail-SAFE to FALSE (1) on any uncertainty (no path / no transcript dir / find missing)
# so normal stale-worktree removal is never blocked; the window is the only safety margin.
_WORKTREE_SESSION_WINDOW_MIN="${HARNESS_WORKTREE_SESSION_WINDOW_MIN:-30}"
worktree_has_live_session() {
  local wt="$1"
  [ -n "$wt" ] || return 1
  command -v find >/dev/null 2>&1 || return 1
  local abs; abs=$(cd "$wt" 2>/dev/null && pwd -P) || abs="$wt"
  local enc; enc=$(printf '%s' "$abs" | tr -c '[:alnum:]' '-')
  local sdir="$HOME/.claude/projects/$enc"
  [ -d "$sdir" ] || return 1
  [ -n "$(find "$sdir" -maxdepth 1 -name '*.jsonl' -mmin "-${_WORKTREE_SESSION_WINDOW_MIN}" 2>/dev/null | head -n1)" ]
}
