"""harness-as — Action Surface (AS) axis.

Public API re-exports. Authority: harness-as/CLAUDE.md; AS plan v1.
"""

from harness_as.anthropic_attribute_namespaces import (
    AttributeNamespace,
    AttributeSchema,
    SkillVersionValidationResult,
    namespace_schema,
    validate_skill_attributes_carry_both_version_fields,
)
from harness_as.anthropic_primitive_adoption import (
    ADOPTION_DEPTH_MATRIX,
    ANTHROPIC_PRIMITIVE_ANCHORS,
    AdoptionDepth,
    AdoptionDepthBinding,
    AnchorCitation,
    AnthropicPrimitive,
    ConfidenceTag,
    adoption_depth,
    skills_loads_from_filesystem_path,
)
from harness_as.blast_radius_floor import blast_radius_floor
from harness_as.cross_deployment_monotonicity import (
    GovernanceViolation,
    GovernanceViolationKind,
    PersonaTierFloor,
    TierRaiseResult,
    bridging_arc_effective_tier_raise,
    detect_tier_downgrade_governance_violation,
    persona_tier_traversal_ascends,
)
from harness_as.deployment_matrix import (
    DEPLOYMENT_MATRIX,
    DeploymentMatrixCell,
    lookup_cell,
    lookup_cell_with_forcing,
)
from harness_as.discriminators import DeploymentSurface, MCPTransport, PersonaTier
from harness_as.engine_class_composition import (
    ENGINE_CLASS_COMPOSITION_OVERLAY,
    MODEL_BINDING_MATRIX,
    MODEL_TIER_ESCALATION_CHAIN,
    PRE_HITL_ESCALATION_ORDER,
    AnthropicModel,
    D1EngineClass,
    EngineClassComposition,
    ModelBinding,
    PreHITLEscalationStep,
    SubAgentRole,
    model_binding,
)
from harness_as.forced_tier_resolution import (
    ForcedTierCause,
    ForcedTierResult,
    ToolContext,
    forced_tier,
)
from harness_as.gate_level_composition import (
    GateLevel,
    GateLevelFloorInterfaces,
    gate_level,
    tier_to_gate_level_floor,
)
from harness_as.mcp_transport_floor import mcp_transport_floor, rejects_at_registration
from harness_as.operator_policy_override_scope import (
    OverrideScopeResult,
    override_scope,
)
from harness_as.sandbox_fail_class import (
    C5FailClass,
    C9RetryPosture,
    SandboxFailClass,
    SandboxFailClassMetadata,
    fail_class_metadata,
    permanent_fail_skips_staircase,
)
from harness_as.sandbox_provider_class import (
    ClassCardinality,
    ProviderClassMetadata,
    SandboxProviderClass,
    provider_class_metadata,
)
from harness_as.sandbox_tier import (
    BlastRadiusTier,
    MechanismClass,
    SandboxTier,
    SandboxTierMetadata,
    is_tier_at_or_above,
    tier_metadata,
)
from harness_as.sandbox_tier_composition import (
    AssignedTierReason,
    CallSiteContext,
    FloorInterfaces,
    SandboxTierCompositionOutcome,
    SandboxTierCompositionResult,
    TaintState,
    sandbox_tier,
)
from harness_as.sandbox_tier_floor import (
    REFUSE,
    MCPServer,
    MCPServerTrustLevel,
    SandboxTierFloorOutcome,
    SandboxTierFloorResult,
    ToolMetadata,
    sandbox_tier_floor,
)
from harness_as.secret_allowlist import AllowlistDecision, check_secret_allowlist
from harness_as.secret_fail_class import (
    SECRET_FAIL_CLASS_METADATA,
    SecretBackendBreakerKey,
    SecretC5FailClass,
    SecretC9RetryPosture,
    SecretFailClass,
    SecretFailClassMetadata,
    construct_breaker_key,
    secret_fail_class_metadata,
)
from harness_as.secret_fetch import (
    TIER_RESOLUTION_TABLE,
    SecretRef,
    SecretResolutionMechanism,
    SecretScope,
    TierResolutionMechanism,
    TPerm2Pole,
    fetch_secret,
    tier_resolution_mechanism,
)
from harness_as.secret_fetch_audit import (
    SecretFetchEvent,
    compose_secret_fetch_audit_entry,
    verify_secret_fetch_entry_in_chain,
)
from harness_as.secret_outputs_hash import (
    canonicalize_concat_secret_fingerprint,
    compute_outputs_hash,
)
from harness_as.sub_agent_sandbox_tier import (
    SubAgentBoundaryViolation,
    SubAgentBoundaryViolationKind,
    detect_sub_agent_tier_downgrade,
    sub_agent_sandbox_tier,
)
from harness_as.tool_contract import (
    RECOMMENDED_CONTRACT_DEFAULT_TIER,
    ContractValidationOutcome,
    ContractValidationResult,
    JSONSchema,
    RawContractInput,
    SecretAllowlistEntry,
    ToolContract,
    validate_tool_contract_at_registration,
)

__all__ = [
    "ADOPTION_DEPTH_MATRIX",
    "ANTHROPIC_PRIMITIVE_ANCHORS",
    "DEPLOYMENT_MATRIX",
    "ENGINE_CLASS_COMPOSITION_OVERLAY",
    "MODEL_BINDING_MATRIX",
    "MODEL_TIER_ESCALATION_CHAIN",
    "PRE_HITL_ESCALATION_ORDER",
    "RECOMMENDED_CONTRACT_DEFAULT_TIER",
    "REFUSE",
    "SECRET_FAIL_CLASS_METADATA",
    "TIER_RESOLUTION_TABLE",
    "AdoptionDepth",
    "AdoptionDepthBinding",
    "AllowlistDecision",
    "AnchorCitation",
    "AnthropicModel",
    "AnthropicPrimitive",
    "AssignedTierReason",
    "AttributeNamespace",
    "AttributeSchema",
    "BlastRadiusTier",
    "C5FailClass",
    "C9RetryPosture",
    "CallSiteContext",
    "ClassCardinality",
    "ConfidenceTag",
    "ContractValidationOutcome",
    "ContractValidationResult",
    "D1EngineClass",
    "DeploymentMatrixCell",
    "DeploymentSurface",
    "EngineClassComposition",
    "FloorInterfaces",
    "ForcedTierCause",
    "ForcedTierResult",
    "GateLevel",
    "GateLevelFloorInterfaces",
    "GovernanceViolation",
    "GovernanceViolationKind",
    "JSONSchema",
    "MCPServer",
    "MCPServerTrustLevel",
    "MCPTransport",
    "MechanismClass",
    "ModelBinding",
    "OverrideScopeResult",
    "PersonaTier",
    "PersonaTierFloor",
    "PreHITLEscalationStep",
    "ProviderClassMetadata",
    "RawContractInput",
    "SandboxFailClass",
    "SandboxFailClassMetadata",
    "SandboxProviderClass",
    "SandboxTier",
    "SandboxTierCompositionOutcome",
    "SandboxTierCompositionResult",
    "SandboxTierFloorOutcome",
    "SandboxTierFloorResult",
    "SandboxTierMetadata",
    "SecretAllowlistEntry",
    "SecretBackendBreakerKey",
    "SecretC5FailClass",
    "SecretC9RetryPosture",
    "SecretFailClass",
    "SecretFailClassMetadata",
    "SecretFetchEvent",
    "SecretRef",
    "SecretResolutionMechanism",
    "SecretScope",
    "SkillVersionValidationResult",
    "SubAgentBoundaryViolation",
    "SubAgentBoundaryViolationKind",
    "SubAgentRole",
    "TPerm2Pole",
    "TaintState",
    "TierRaiseResult",
    "TierResolutionMechanism",
    "ToolContext",
    "ToolContract",
    "ToolMetadata",
    "adoption_depth",
    "blast_radius_floor",
    "bridging_arc_effective_tier_raise",
    "canonicalize_concat_secret_fingerprint",
    "check_secret_allowlist",
    "compose_secret_fetch_audit_entry",
    "compute_outputs_hash",
    "construct_breaker_key",
    "detect_sub_agent_tier_downgrade",
    "detect_tier_downgrade_governance_violation",
    "fail_class_metadata",
    "fetch_secret",
    "forced_tier",
    "gate_level",
    "is_tier_at_or_above",
    "lookup_cell",
    "lookup_cell_with_forcing",
    "mcp_transport_floor",
    "model_binding",
    "namespace_schema",
    "override_scope",
    "permanent_fail_skips_staircase",
    "persona_tier_traversal_ascends",
    "provider_class_metadata",
    "rejects_at_registration",
    "sandbox_tier",
    "sandbox_tier_floor",
    "secret_fail_class_metadata",
    "skills_loads_from_filesystem_path",
    "sub_agent_sandbox_tier",
    "tier_metadata",
    "tier_resolution_mechanism",
    "tier_to_gate_level_floor",
    "validate_skill_attributes_carry_both_version_fields",
    "validate_tool_contract_at_registration",
    "verify_secret_fetch_entry_in_chain",
]
